version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run:
          name: "print workflow ID"
          command: "echo $CIRCLE_WORKFLOW_ID"

jobs:
  print-id:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id

workflows:
  say-hello-workflow:
    jobs:
      - print-id
