version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run:
          name: "print workflow ID"
          command: "$CIRCLE_WORKFLOW_ID"

jobs:
  print-id:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "print workflow ID"
          command: "$CIRCLE_WORKFLOW_ID"
      - run:
          name: "job fail"
          command: "echo the job has failed"
          when: on_fail
      

workflows:
  say-hello-workflow:
    jobs:
      - print-id
