---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install npm"
  become: yes
  apt:
    name: npm
    state: latest

- name: "install nodejs"
  become: yes
  apt:
    name: nodejs
    state: latest

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest

- name: "create web directory"
  ansible.builtin.file:
    path: ~/web
    state: directory

- name: "copy index test page"
  copy:
    src: files/index.js
    dest: ~/web/index.js

- name: "start web server"
  become: yes
  command: pm2 start ~/web/index.js -f